In [7]:
import torch
import numpy as np

In [10]:
zeros = torch.zeros((2,3))
ones = torch.ones((2,3))
rand = torch.rand((2,3))

print(zeros)
print(ones)
print(rand)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.6748, 0.0475, 0.2206],
        [0.5637, 0.5814, 0.0612]])


In [12]:
a = torch.tensor([[1., 2.], [3., 4.]])
b = torch.tensor([[5.,6.], [7., 8.]])

print(a)
print(b)
print(a+b)
print(a*b) #mnozenie elementowe
print(a @ b.T) #iloczyn macierzowy

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])
tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[17., 23.],
        [39., 53.]])


In [ ]:
t= torch.arange(12).reshape(3,4)
print(t)
print(t.reshape(2,6)) #nowy ksztalt, kopijuje dane
print(t.view(2,6)) #ten sam tensor ale inny widok, nie kopijuje

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [ ]:
arr = np.array([1,2,3])
t1 = torch.tensor(arr) #kopia, nie widac updatu bo stara kopia
t2 = torch.as_tensor(arr) # wspoldzielona pamiec, czyli widac update
arr[0]=67
print(t1,t2)

tensor([1, 2, 3]) tensor([67,  2,  3])


In [9]:
def tensor_operations_demo(t):
    mean_val = t.mean()
    std_val = t.std()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    t_device = t.to(device)

    print(f"Średnia: {mean_val:.4f}, Odchylenie: {std_val:.4f}")
    print(f"Tensor znajduje się na urządzeniu: {t_device.device}")

    return mean_val,std_val,t_device

my_tensor = torch.randn(100) #tworzy tensor 100 losowych liczb
tensor_operations_demo(my_tensor)

Średnia: 0.0637, Odchylenie: 1.1191
Tensor znajduje się na urządzeniu: cpu


(tensor(0.0637),
 tensor(1.1191),
 tensor([ 0.1868, -1.4394,  0.1025,  0.1314,  0.2977, -0.1985, -2.0944,  0.5395,
         -1.8340,  2.5568, -1.3764,  0.2957,  0.6446, -0.3985, -0.3590, -1.4435,
         -1.3716, -0.0841,  0.0948,  0.0404,  0.1708,  0.6569,  0.0194,  1.1014,
          1.4683, -0.0320,  1.7150, -0.2924,  1.1280,  0.1612,  0.7800, -0.3903,
         -1.2276, -0.3392,  1.0389, -0.1282, -1.0565, -1.5275, -0.6009,  0.1813,
         -0.4969, -0.7826,  0.9884,  0.0755,  1.3079, -0.2811, -0.6930,  1.5001,
          0.7953, -0.3413,  1.6702,  2.5383,  0.1497, -0.5537,  0.9492,  0.3930,
         -0.3949,  0.3374,  1.3274, -0.2713, -0.9935, -0.9742, -0.6596,  0.5477,
         -1.7908, -0.0185,  1.5802,  0.4254,  1.7728, -0.0495,  0.3059, -0.2954,
          0.8427, -0.2757, -1.8243, -1.0345, -1.6754,  2.1648,  1.5247,  1.6983,
         -2.5552,  3.3655, -0.0614, -1.8826,  0.8749,  1.4833, -0.4308, -0.4745,
          0.3973,  0.3934,  0.6199,  1.7669, -0.2558, -1.4075, -0.5605, -0.